CarProject/Controllers/CarinformationController.cs
using MongoDB.Bson;
using MongoDB.Driver;
using MongoDB.Driver.Builders;
using MongoDemo.App_Start;
using MongoDemo.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MongoDemo.Controllers
{
    public class CarinformationController : Controller
    {
        MongoContext _dbContext;
        public CarinformationController()
        {
            _dbContext = new MongoContext();
        }

        public ActionResult Index()
        {
            var carDetails = _dbContext._database.GetCollection<CarModel>("CarModel").FindAll().ToList();
            return View(carDetails);
        }



        public ActionResult Create()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }

        [HttpPost]
        public ActionResult Create(CarModel carmodel)
        {
            var document = _dbContext._database.GetCollection<BsonDocument>("CarModel");
            var query = Query.And(Query.EQ("Carname", carmodel.Carname), Query.EQ("Color", carmodel.Color));

            var count = document.FindAs<CarModel>(query).Count();

            if (count == 0)
            {
                var result = document.Insert(carmodel);
                return RedirectToAction("Index");

            }
            else
            {
                TempData["AlertMessage"] = "  İslem Basarılı";
                return RedirectToAction("Index");
            }
            
        }

        public ActionResult Edit(string id)
        {
            var document = _dbContext._database.GetCollection<CarModel>("CarModel");

            var carDetailscount = document.FindAs<CarModel>(Query.EQ("_id", new ObjectId(id))).Count();

            if (carDetailscount > 0)
            {
                var carObjectid = Query<CarModel>.EQ(p => p.Id, new ObjectId(id));

                var carDetail = _dbContext._database.GetCollection<CarModel>("CarModel").FindOne(carObjectid);

                return View(carDetail);
            }
            return RedirectToAction("Index");
        }
        [HttpPost]
        public ActionResult Edit(string id, CarModel carmodel)
        {
            try
            {
                carmodel.Id = new ObjectId(id);
                //Mongo Query  
                var CarObjectId = Query<CarModel>.EQ(p => p.Id, new ObjectId(id));
                // Document Collections  
                var collection = _dbContext._database.GetCollection<CarModel>("CarModel");
                // Document Update which need Id and Data to Update  
                var result = collection.Update(CarObjectId, Update.Replace(carmodel), UpdateFlags.None);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        public ActionResult Details(string id)
        {
            var carId = Query<CarModel>.EQ(p => p.Id, new ObjectId(id));
            var carDetail = _dbContext._database.GetCollection<CarModel>("CarModel").FindOne(carId);
            return View(carDetail);
        }
        public ActionResult Delete(string id)
        {
            var carObjectId = Query<CarModel>.EQ(p => p.Id, new ObjectId(id));
            var carDetail = _dbContext._database.GetCollection<CarModel>("CarModel")
                .FindOne(carObjectId);
            return View(carDetail);
        }
        // POST: Carinformation/Delete/5  
        [HttpPost]
        public ActionResult Delete(string id, CarModel CarModel)
        {
            try
            {
                //Mongo Query  
                var carObjectid = Query<CarModel>.EQ(p => p.Id, new ObjectId(id));
                // Document Collections  
                var collection = _dbContext._database.GetCollection<CarModel>("CarModel");
                // Document Delete which need ObjectId to Delete Data   
                var result = collection.Remove(carObjectid, RemoveFlags.Single);

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

    }
}

CarProject/Views/Carinformation/Create.cshtml
@model MongoDemo.Models.CarModel

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>CarModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Carname, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Carname, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Carname, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Color, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Color, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Color, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Engineno, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Engineno, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Engineno, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Registrationno, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Registrationno, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Registrationno, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RegistrationDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RegistrationDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RegistrationDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Model, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Model, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Model, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Chassisno, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Chassisno, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Chassisno, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CarProject/Views/Carinformation/Delete.cshtml
@model MongoDemo.Models.CarModel

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>CarModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Carname)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Carname)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Color)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Color)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Engineno)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Engineno)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Registrationno)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Registrationno)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RegistrationDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RegistrationDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Model)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Model)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Chassisno)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Chassisno)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

CarProject/Views/Carinformation/Details.cshtml
@model MongoDemo.Models.CarModel

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>CarModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Carname)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Carname)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Color)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Color)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Engineno)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Engineno)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Registrationno)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Registrationno)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RegistrationDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RegistrationDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Model)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Model)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Chassisno)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Chassisno)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Back to List", "Index")
</p>

CarProject/Views/Carinformation/Edit.cshtml
@model MongoDemo.Models.CarModel

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>CarModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Carname, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Carname, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Carname, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Color, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Color, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Color, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Engineno, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Engineno, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Engineno, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Registrationno, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Registrationno, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Registrationno, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RegistrationDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RegistrationDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RegistrationDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Model, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Model, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Model, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Chassisno, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Chassisno, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Chassisno, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CarProject/Views/Carinformation/Index.cshtml
@model IEnumerable<MongoDemo.Models.CarModel>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Carname)
        </th>

    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Carname)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Color)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Price)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Engineno)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Registrationno)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.RegistrationDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Model)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Chassisno)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Carname)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Color)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Price)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Engineno)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Registrationno)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.RegistrationDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Model)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Chassisno)
            </td>

            <td>@Html.ActionLink("Details", "Details", "Carinformation", new { @id = item.Id }, new { @class = "btn btn-success" })</td>
            <td>@Html.ActionLink("Edit", "Edit", "Carinformation", new { @id = item.Id }, new { @class = "btn btn-danger" })</td>
            <td>@Html.ActionLink("Delete", "Delete", "Carinformation", new { @id = item.Id }, new { @class = "btn btn-info" })</td>
        </tr>
    }

</table>

<th>
    @Html.DisplayNameFor(model => model.Color)
</th>
<th>
    @Html.DisplayNameFor(model => model.Price)
</th>
<th>
    @Html.DisplayNameFor(model => model.Engineno)
</th>
<th>
    @Html.DisplayNameFor(model => model.Registrationno)
</th>
<th>
    @Html.DisplayNameFor(model => model.RegistrationDate)
</th>
<th>
    @Html.DisplayNameFor(model => model.Model)
</th>
<th>
    @Html.DisplayNameFor(model => model.Chassisno)
</th>
<th></th>
  

@foreach (var item in Model)
{
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Carname)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Color)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Price)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Engineno)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Registrationno)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.RegistrationDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Model)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Chassisno)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
        </td><
    </tr>
}